// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $r_roomName_ from "./routes/r/[roomName].tsx";
import * as $EnterRoomUI from "./islands/EnterRoomUI.tsx";
import * as $RoomIsland from "./islands/RoomIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/r/[roomName].tsx": $r_roomName_,
  },
  islands: {
    "./islands/EnterRoomUI.tsx": $EnterRoomUI,
    "./islands/RoomIsland.tsx": $RoomIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
