name: Docker Build and Publish

on:
    push:
        branches:
            - main
    workflow_dispatch:
        # Allows manual triggering

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build with Deno and Docker
              run: |
                  deno task build
                  docker build --build-arg GIT_REVISION=${{ github.sha }} -t gjtiquia/ijustwannacopypaste:latest .

            - name: Push to Docker Hub
              run: docker push gjtiquia/ijustwannacopypaste:latest
