name: Railway Deploy

on:
    workflow_run:
        workflows: ["Docker Build and Publish"]
        types:
            - completed
        branches:
            - main
    workflow_dispatch:
        # Allows manual triggering

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

        steps:
            - name: Trigger Railway Deployment
              run: |
                echo "Triggering Railway deployment..."
                RESPONSE=$(curl --fail --request POST \
                  --url https://backboard.railway.app/graphql/v2 \
                  --header 'Content-Type: application/json' \
                  --header 'Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}' \
                  --data '{
                    "query": "mutation serviceInstanceDeploy($serviceId: String!, $environmentId: String!) { serviceInstanceDeploy(serviceId: $serviceId, environmentId: $environmentId) }",
                    "variables": {
                      "environmentId": "${{ secrets.RAILWAY_ENVIRONMENT_ID }}",
                      "serviceId": "${{ secrets.RAILWAY_SERVICE_ID }}"
                    }
                  }')
                
                echo "Response from Railway:"
                echo "$RESPONSE" | jq '.'
                
                if ! echo "$RESPONSE" | jq -e '.data.serviceInstanceDeploy' > /dev/null; then
                  echo "Error: Deployment failed"
                  exit 1
                fi
                
                echo "Deployment triggered successfully" 