name: Railway Deploy

on:
    workflow_run:
        workflows: ["Docker Build and Publish"]
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Get Latest Deployment ID
              id: get-deployment
              run: |
                DEPLOYMENT_ID=$(curl --request POST \
                  --url https://backboard.railway.app/graphql/v2 \
                  --header 'Content-Type: application/json' \
                  --header 'Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}' \
                  --data '{"query":"query { deployments(first: 1, input: { projectId: \"${{ secrets.RAILWAY_PROJECT_ID }}\", environmentId: \"${{ secrets.RAILWAY_ENVIRONMENT_ID }}\", serviceId: \"${{ secrets.RAILWAY_SERVICE_ID }}\" }) { edges { node { id } } } }"}' \
                  | jq -r '.data.deployments.edges[0].node.id')
                echo "deployment_id=$DEPLOYMENT_ID" >> "$GITHUB_OUTPUT"

            - name: Restart Deployment
              run: |
                curl --request POST \
                  --url https://backboard.railway.app/graphql/v2 \
                  --header 'Content-Type: application/json' \
                  --header 'Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}' \
                  --data "{\"query\":\"mutation { deploymentRestart(id: \\\"${{ steps.get-deployment.outputs.deployment_id }}\\\") }\"}" 